### ISSUE TITLE
Why not `go run file.go -flag ...`?

### ISSUE THREAD

**Issue by philoserf** [mbertschler/run#1]
This capability exists with `go run file.go -flag ...`

**Comment by mbertschler** [comment]
For me personally because of two reasons:

#### 1. This will only work with single file programs

If you want to use it with a multi file package you would have to do something hacky like
`go run $(find . -name "*.go" -and -not -name "*_test.go" -maxdepth 1)` (Taken from https://stackoverflow.com/questions/23695448/golang-run-all-go-files-within-current-directory-through-the-command-line-mul)

#### 2. This is dependent of the current working directory

I often use this tool from various directories that contain the files I want to operate on. Since this is outside of my $GOPATH the path to the `go run` file would be often pretty long. This tool uses the standard $GOPATH organization, which makes it independent of the working directory.

Thanks for the question!
